[package]
name = "scheduled-charge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
futures-util = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
zbus = "4.4.0"
zbus_systemd = { version = "0.25600.0", features = ["login1"] }
